[2021-06-21 15:18:36] Exception was thrown: <Could not connect to database>
se.kth.iv1350.pos.integration.InventoryFailureException: Could not connect to database
	at se.kth.iv1350.pos.integration.ExternalInventorySystem.fetchItem(ExternalInventorySystem.java:63)
	at se.kth.iv1350.pos.controller.Controller.addNewItem(Controller.java:58)
	at se.kth.iv1350.pos.view.View.fakeAddItem(View.java:85)
	at se.kth.iv1350.pos.view.View.runFakeExecution(View.java:52)
	at se.kth.iv1350.pos.startup.Main.main(Main.java:30)

[2021-06-21 15:18:36] Exception was thrown: <Could not connect to database>
se.kth.iv1350.pos.integration.InventoryFailureException: Could not connect to database
	at se.kth.iv1350.pos.integration.ExternalInventorySystem.fetchItem(ExternalInventorySystem.java:63)
	at se.kth.iv1350.pos.controller.Controller.addNewItem(Controller.java:58)
	at se.kth.iv1350.pos.view.View.fakeAddItem(View.java:85)
	at se.kth.iv1350.pos.view.View.runFakeExecution(View.java:52)
	at se.kth.iv1350.pos.startup.Main.main(Main.java:31)

